//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVACart.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.EvacArtists = new HashSet<EvacArtists>();
            this.Events = new HashSet<Event>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<bool> BoardingAvailable { get; set; }
        public int ArtistID { get; set; }
        public int StaffID { get; set; }
    
        //public virtual EvacArtists EvacArtists { get; set; }
        //public virtual Staff Staff { get; set; }
        public virtual ICollection<EvacArtists> EvacArtists { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
