//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVACart.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public int DepartmentID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int GalleryID { get; set; }
        public int ArtistID { get; set; }
        public int StaffID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EvacArtists EvacArtists { get; set; }
        public virtual Gallery Gallery { get; set; }
    }
}
